//--------------------------------------------------------------------
// MEDIUM — combining syntax to understand a line/short block
//--------------------------------------------------------------------
.quiz.syntaxIntraday.medium:`appendUpsert`disksortLine`endLoop`iascLogic`firstLastCheck`vSetLine`genQueryMemFlag`winClause`unEnumAmend`appendColGuard`appendTableDfile`chkCalls!
    (
    `question`answers`correct!(
        "What does the expression .[` sv TMPSAVE,t,`;();,;.Q.en[`:.]`. x] do as a whole?";

        `a`b`c`d!(
            "Amends the splayed table at TMPSAVE/t on disk by appending (,) the enumerated in-memory table x to it";
            "Deletes the splayed table at TMPSAVE/t and replaces it with x";
            "Reads the splayed table at TMPSAVE/t into memory as x";
            "Sorts the splayed table at TMPSAVE/t using x as the sort key"
        );

        `a
    );

    `question`answers`correct!(
        "In the expression .[dir;`sym;`p#], what would change if `p# were replaced with `s#?";

        `a`b`c`d!(
            "The sym column would get a sorted attribute instead of a parted attribute, which is not appropriate once data spans multiple syms";
            "Nothing — `p# and `s# are interchangeable in kdb+";
            "It would enumerate the sym column instead of attributing it";
            "It would apply the attribute to the whole table instead of one column"
        );

        `a
    );

    `question`answers`correct!(
        "In disksort, what does ii:iasc iasc flip c!t c,:() compute?";

        `a`b`c`d!(
            "The grade (sort order) of the values in column c of table t, used to reorder the whole table consistently";
            "A count of unique values in column c";
            "The reverse-sorted values of column c";
            "A dictionary mapping column c to itself"
        );

        `a
    );

    `question`answers`correct!(
        "In disksort, what is being checked by (0,-1+count ii)~(first;last)@\\:ii?";

        `a`b`c`d!(
            "Whether the grade vector ii is already the identity order, i.e. the column is already sorted";
            "Whether ii contains any duplicate indices";
            "Whether the first and last rows of the table are equal";
            "Whether the column has an existing `p# attribute"
        );

        `a
    );

    `question`answers`correct!(
        "In disksort's column-uniqueness check, what does all(fv:first v)~/:256#v test?";

        `a`b`c`d!(
            "Whether the first 256 values of v are all identical to the first value";
            "Whether v has at least 256 rows";
            "Whether v is sorted in ascending order";
            "Whether v contains exactly 256 distinct values"
        );

        `a
    );

    `question`answers`correct!(
        "What does the line v[x]:v; y set v do after the uniqueness check fails in disksort?";

        `a`b`c`d!(
            "Reorders the column's values v by the grade x and writes the reordered vector back to disk at path y";
            "Deletes the column from disk";
            "Replaces every value in v with the value at index x";
            "Copies v to a new column named y"
        );

        `a
    );

    `question`answers`correct!(
        "In genQuery, what does memFlag:st>LASTTIME[t;s] compute?";

        `a`b`c`d!(
            "For each requested sym, whether the query's start time is later than the last time written to disk — meaning the whole interval is in memory";
            "Whether the current time is later than LASTTIME";
            "The number of syms whose data is only on disk";
            "Whether table t exists in .mem"
        );

        `a
    );

    `question`answers`correct!(
        "What is the purpose of win:enlist(within;`time;(st;et)) in genQuery?";

        `a`b`c`d!(
            "Builds a functional Where-clause term restricting time to the (st;et) interval";
            "Builds a list of window sizes for aggregation";
            "Defines the columns to select";
            "Converts st and et into enumerated values"
        );

        `a
    );

    `question`answers`correct!(
        "In unEnum, what does @[t;c;:;sym@t[c]] do when 20=type t[c]?";

        `a`b`c`d!(
            "Replaces column c in table t with its un-enumerated symbol values, using the sym list to look them up";
            "Deletes column c from table t";
            "Enumerates column c against the sym list";
            "Sorts column c in table t by its enumerated values"
        );

        `a
    );

    `question`answers`correct!(
        "In appendCol, what does the guard if[not col like\"*#\";...] prevent?";

        `a`b`c`d!(
            "It stops the function from trying to append `#` (length) columns, which are auto-generated by kdb+ for list columns";
            "It stops non-numeric columns from being appended";
            "It prevents columns already on disk from being overwritten";
            "It skips appending the sym column specifically"
        );

        `a
    );

    `question`answers`correct!(
        "In appendTable, what does @[hdb;`.d;:;`sym`time,get[...]except`time`sym] achieve?";

        `a`b`c`d!(
            "Writes a new .d file to the HDB table, putting sym and time first followed by the remaining columns in their original order";
            "Deletes the .d file from the HDB table";
            "Copies the .d file from the temporary directory unchanged";
            "Sorts the .d file's columns alphabetically"
        );

        `a
    );

    `question`answers`correct!(
        "Where does .Q.chk get called in the partitioned writedown solution, and why in each case?";

        `a`b`c`d!(
            "In writeToTmp when a new table/partition appears, and in appendHDB after appending — both times to ensure all tables/columns exist consistently across partitions";
            "Only once, at RDB startup, to validate the sym file";
            "Only in .u.end, to replay the tickerplant log";
            "Only in disksort, to validate column order"
        );

        `a
    )
 );